name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          export MONGO_URI="mongodb://localhost:27017/taskmanager"
          pytest

      - name: Deploy to Heroku
        if: github.ref == 'refs/heads/main'
        run: |
          wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
          echo "$HEROKU_API_KEY" | docker login --username=$HEROKU_EMAIL --password-stdin registry.heroku.com
          heroku container:push web --app $HEROKU_APP_NAME
          heroku container:release web --app $HEROKU_APP_NAME
